name: flutter_game_module
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audioplayers: ^6.0.0
  # Dependence Injection
  get_it: ^7.7.0
  haptic_feedback: ^0.5.1+1

  flip_card: ^0.7.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka-300.ttf
          weight: 300
        - asset: assets/fonts/fredoka-400.ttf
          weight: 400
        - asset: assets/fonts/fredoka-500.ttf
          weight: 500
        - asset: assets/fonts/fredoka-700.ttf
          weight: 700
        - asset: assets/fonts/fredoka-800.ttf
          weight: 800


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.flutter_game_module
    iosBundleIdentifier: com.example.flutterGameModule
